---
# Start service
- name: start nginx
  service: 
    name: nginx
    state: started
    enabled: yes
- name: start mariadb
  service: 
    name: mariadb
    state: started
    enabled: yes
- name: start php-fpm
  service:
    name: php-fpm
    state: started
    enabled: yes
# Restart services
- name: restart nginx
  service: 
    name: nginx
    state: restarted
- name: restart mariadb
  service: 
    name: mariadb
    state: restarted
- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted