---
# Check dir
- name: Ansible check directory.
  stat:
    path: "{{ ssl_folder }}"
  register: source_folder

- name: "Echo if directory already existed"
  debug:
    msg: "Root Folder is already existed"
  when: source_folder.stat.exists

- name: "Ansible Create directory if not exists"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: nginx
    owner: nginx
  with_items:
    - "{{ ssl_folder }}"
  when: source_folder.stat.exists == false

# Copy Cert
- name: Copy Cert
  copy:
    src: "{{ item }}"
    dest: "{{ ssl_folder }}"
    owner: root
    group: root
    mode: 0755
  with_fileglob:
    - ./roles/add_ssl/files/*