---
# Check dir
- name: Ansible check directory.
  stat:
    path: "{{ ssl_folder }}/live/{{ domain_name }}"
  register: ssl_folder

- name: "Echo if directory already existed"
  debug:
    msg: "Root Folder is already existed"
  when: ssl_folder.stat.exists

- name: "Ansible Create directory if not exists"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: nginx
    owner: nginx
  with_items:
    - "{{ ssl_folder }}"
  when: ssl_folder.stat.exists == false

# Copy Cert
- name: Copy Cert
  copy:
    src: "{{ item }}"
    dest: "{{ ssl_folder }}/live/{{ domain_name }}"
    owner: root
    group: root
    mode: 0755
  with_fileglob:
    - ./roles/add_ssl/files/*

- name: Download foo.conf
  get_url:
    url: https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
    dest: "{{ ssl_folder }}"
    mode: '0644'
  
- name: Download foo.conf
  get_url:
    url: https://raw.githubusercontent.com/certbot/certbot/master/certbot/certbot/ssl-dhparams.pem
    dest: "{{ ssl_folder }}"
    mode: '0644'

